### ISSUE TITLE
Expired Slack link in the engineering team page.

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-handbook#15]
**Describe the bug**
Expired Slack link in the engineering team page.

![Screenshot 2022-11-14 220424](https://user-images.githubusercontent.com/88109775/201714665-55b3cb9e-d047-46c2-b78d-ed4e2142d314.png)

![Screenshot 2022-11-14 214644](https://user-images.githubusercontent.com/88109775/201712599-d169716a-2686-46e8-a8f5-b9e0e392341f.png)

**Describe the solution you'd like**
Replace the expired slack link with an active link.
There is an active slack link you can find in the sef-site join us page.

**Expected behavior**

![proposed sol](https://user-images.githubusercontent.com/88109775/201713869-115a7d6a-35b2-4386-9603-09a697eabd75.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
@jayasanka-sack Shall I work on this ?

**Comment by anjula-sack** [comment]
> @jayasanka-sack Shall I work on this ?

Sure, Let me provide you the link.

**Comment by anjula-sack** [comment]
https://join.slack.com/t/sefheadquarters/shared_invite/zt-1jwub1lpd-RXYAMG46qXRUhOGZ7u_ewg Here's the link @janithlahirukariyawasam

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @jayasanka-sack please close this issue because its done
