### ISSUE TITLE
Check all the expired links in the SEF handbook Repo

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/sef-handbook#17]
**Describe the bug**
I checked all the links that direct to different outside entities such as SEF's Fb profile, SEF hive , other resources (github doc) & etc. 
All the links are up-to-date except the slack link on the navbar.

**To Reproduce**
1. Go to SEF handbook
2. Click on slack in the navbar
 (Please make sure to open the link in a private window ( incognito tab))
3. See error

**Expected behavior**
Update the outdated slack link on the **docusaurus.config.js** file.
![issue 2 sc](https://user-images.githubusercontent.com/88109775/202229817-5236d98c-c9e3-4ed9-bf71-19d66685351c.png)

**Screenshots**

![issue 2](https://user-images.githubusercontent.com/88109775/202226877-07e98f46-1ab8-4310-8a30-e8f42fcd9fe8.png)
![issue 2 error](https://user-images.githubusercontent.com/88109775/202226973-220ddba2-1c77-435d-81bb-2fc36e4dd6fb.png)

**Are you working on it?**
Yes

**Comment by janithlahirukariyawasam** [comment]
Shall I fix this bug? after that all the links are up-to-date.
@jayasanka-sack

**Comment by anjula-sack** [comment]
> Shall I fix this bug? after that all the links are up-to-date. @jayasanka-sack

Go ahead! @janithlahirukariyawasam

**Comment by anjula-sack** [comment]
Fixed with https://github.com/sef-global/sef-handbook/pull/18
