### ISSUE TITLE
Add the purpose section to the pull request template

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-handbook#19]
**Is your feature request related to a problem? Please describe.**
- We haven't added a section to link the relevant GitHub issue in the PR template

**Describe the solution you'd like**
- Add the following section at the top in the [PR template](https://github.com/sef-global/sef-handbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

```
Purpose
The purpose of this PR is to fix #
```

- Refer to this PR [template](https://github.com/sef-global/sef-site/blob/master/.github/pull_request_template.md) 

**Are you working on it?**
No

**Comment by anjula-sack** [comment]
@tharindu37 can you work on this?

**Comment by Tharindu37** [comment]
@anjula-sack Sure

**Comment by YoshithaRathnayake** [comment]
@anjula-sack can you close this issue bcs its completed I can't do that action.
