### ISSUE TITLE
Add Feature request and bug report templates to Sef-handbook repo

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-handbook#2]
**Is your feature request related to a problem? Please describe.**
Currently, the Sef-handbook repo does not have a feature request and bug report template unlike other repositories

**Describe the solution you'd like**
Adding the same Feature request and bug report templates to the handbook repo

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
Can you take a look at this and assign if it is suitable to work on @anjula-sack

**Comment by anjula-sack** [comment]
> Can you take a look at this and assign if it is suitable to work on @anjula-sack

You can go ahead

**Comment by anjula-sack** [comment]
Fixed with https://github.com/sef-global/sef-handbook/pull/6
