### ISSUE TITLE
Add new "Team Responsibilities" page

### ISSUE THREAD

**Issue by miniskynet** [sef-global/sef-handbook#21]
**Is your feature request related to a problem? Please describe.**
There is no page in the handbook which documents the responsibilities of a team member

**Describe the solution you'd like**
Create a subsection under the "Engineering Team" page, titled "Team Responsibilities", which should contain the content of this newly created [google doc](https://docs.google.com/document/d/1jRCIfa6SMzSPEh-NwxPySYLpu_Ra1co_r6LzBepa1C4/edit)

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by miniskynet** [comment]
@anjula-sack can you please assign @YoshithaRathnayake ?

**Comment by miniskynet** [comment]
Hi @YoshithaRathnayake you can start working on this

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake you can start working on this

Sure @miniskynet
