### ISSUE TITLE
Remove the organization drop down

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-handbook#27]
**Is your feature request related to a problem? Please describe.**
The organization drop down covers all the other menu items

**Describe the solution you'd like**
I'd like to remove the 'Organization' drop down and keep of the elements outside

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
@anjula-sack I'd like to work on this, can you please assign me?

**Comment by anjula-sack** [comment]
> @anjula-sack I'd like to work on this, can you please assign me?

Go ahead! @DilinaBandara
