### ISSUE TITLE
Add Slack link to Handbook Navbar

### ISSUE THREAD

**Issue by dave-v0** [sef-global/sef-handbook#3]
**Is your feature request related to a problem? Please describe.**
Currently the Handbook Navbar does not consist of a Slack link

**Describe the solution you'd like**
Adding a Slack link to the Navbar

**Additional context**
![image](https://user-images.githubusercontent.com/104125359/185778559-5e40e17f-2c2b-4ee6-8df1-4217f08f1532.png)

**Are you working on it?**
Yes

**Comment by dave-v0** [comment]
I'd like to work on this @anjula-sack

**Comment by anjula-sack** [comment]
Fixed with https://github.com/sef-global/sef-handbook/pull/5
