### ISSUE TITLE
Fix the typo in the about us page

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-handbook#30]
**Is your feature request related to a problem? Please describe.**
- There's a small typo on the about us page under the what is SEF section.
<img width="140" alt="image" src="https://user-images.githubusercontent.com/43912578/222962776-cd090351-0a2d-47e6-9997-1bf74fa839f4.png">

**Describe the solution you'd like**
- Fix the typo. `Lakans` -> `Lankans`

**Are you working on it?**
- No

**Comment by Sanjana0823** [comment]
I would like to work on this.

**Comment by anjula-sack** [comment]
> I would like to work on this.

Go ahead, @Sanjana0319
