### ISSUE TITLE
Add the GSoC 2024 Project Ideas table to the handbook

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-handbook#35]
**Is your feature request related to a problem? Please describe.**
We want a GSoC 2024 Project Ideas table in the handbook

**Describe the solution you'd like**
There is a table already in the handbook and you have to replace the table like in this page
https://wiki.openmrs.org/display/RES/Summer+of+Code+2024

And get the details from this document and fill the rest
https://docs.google.com/document/d/1UdKpwBDux04xd0r0LCw9qD-GoCDc6iqBq2ei5kHYjd4/edit?usp=sharing

**Are you working on it?**
No

**Comment by Dilini-457** [comment]
I would like to do this task

**Comment by YoshithaRathnayake** [comment]
> I would like to do this task

Sure, go ahead @Dilini-457

**Comment by YoshithaRathnayake** [comment]
@anjula-sack can you assign? @Dilini-457 bcs I can't do that in handbook

**Comment by Sanjana0823** [comment]
I would like to do this

**Comment by anjula-sack** [comment]
> I would like to do this

Go ahead @Sanjana0319
