### ISSUE TITLE
Add the handbook link to the description in the right side of this repository

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-handbook#8]
**Is your feature request related to a problem? Please describe.**
Currently, there is no link in the description in the right side of this repository

**Describe the solution you'd like**
Add the handbook link to the description in the right side of this repository

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @Piumal1999 @jayasanka-sack @Gravewalker666 can you solve this?

**Comment by jayasanka-sack** [comment]
Done! Thanks @YoshithaRathnayake !! ❤️

**Comment by YoshithaRathnayake** [comment]
> Done! Thanks @YoshithaRathnayake !! ❤️

Your welcome @jayasanka-sack
