### ISSUE TITLE
Change the URL of the handbook page in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/sef-handbook#9]
**Is your feature request related to a problem? Please describe.**
Currently, the link in the readme.md file to redirect to the handbook page is wrong

**Describe the solution you'd like**
Change the URL of the handbook page in the readme.md file

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by jayasanka-sack** [comment]
Sure!
